
name: Qualys IAC Scan 
##
#on : workflow_dispatch
on: 
  push:
    branches:
    - main
  pull_request:
        branches: [ main ] 
#   schedule:
#         - cron:  '*/5 * * * *'


jobs:
    iac_scan:
        runs-on: ubuntu-latest
        name: IaC Scan Connector
        steps:
          - name: Checkout
            uses: actions/checkout@v2 
            with:
                fetch-depth: 0
    
          - name: IAC scan action step
            uses: QIntegration/github_action_qiac@dev/1.1.0
            id: iac
            env:
                URL: ${{ secrets.URL }}
                UNAME: ${{ secrets.USERNAME }}
                PASS: ${{ secrets.PASSWORD }}
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v1
            if: always() 
            with:
                 sarif_file: response.sarif
                 
                 
